--ELIMINAR PROCEDURES
DROP PROCEDURE DB_OWNERS.migrar_usuario;
DROP PROCEDURE DB_OWNERS.migrar_provincias;
DROP PROCEDURE DB_OWNERS.migrar_localidades;
DROP PROCEDURE DB_OWNERS.migrar_direcciones;
DROP PROCEDURE DB_OWNERS.migrar_tipos_local;
DROP PROCEDURE DB_OWNERS.migrar_categorias;
DROP PROCEDURE DB_OWNERS.migrar_categorias_local;
DROP PROCEDURE DB_OWNERS.migrar_locales;
DROP PROCEDURE DB_OWNERS.migrar_dias_semana;
DROP PROCEDURE DB_OWNERS.migrar_horarios_atencion;
DROP PROCEDURE DB_OWNERS.migrar_cupones_reclamo;
DROP PROCEDURE DB_OWNERS.migrar_cupones_usados;
DROP PROCEDURE DB_OWNERS.migrar_datos_tarjeta;
DROP PROCEDURE DB_OWNERS.migrar_direcciones_por_usuario;
DROP PROCEDURE DB_OWNERS.migrar_direcciones2;
DROP PROCEDURE DB_OWNERS.migrar_envio_mensajeria;
DROP PROCEDURE DB_OWNERS.migrar_estado;
DROP PROCEDURE DB_OWNERS.migrar_items;
DROP PROCEDURE DB_OWNERS.migrar_medio_de_pago;
DROP PROCEDURE DB_OWNERS.migrar_movilidad;
DROP PROCEDURE DB_OWNERS.migrar_operador;
DROP PROCEDURE DB_OWNERS.migrar_pedidos;
DROP PROCEDURE DB_OWNERS.migrar_productos;
DROP PROCEDURE DB_OWNERS.migrar_productos_por_local;
DROP PROCEDURE DB_OWNERS.migrar_reclamos;
DROP PROCEDURE DB_OWNERS.migrar_repartidor;
DROP PROCEDURE DB_OWNERS.migrar_tipo_paquete;
DROP PROCEDURE DB_OWNERS.migrar_tipo_reclamo;
DROP PROCEDURE DB_OWNERS.migrar_tipo_cupon
DROP PROCEDURE DB_OWNERS.migrar_cupon




--ELIMINAR TABLAS
DROP TABLE DB_OWNERS.TIPO_CUPON;
DROP TABLE DB_OWNERS.CUPON_USADO;
DROP TABLE DB_OWNERS.CUPON_RECLAMO;
DROP TABLE DB_OWNERS.RECLAMO;
DROP TABLE DB_OWNERS.CUPON;
DROP TABLE DB_OWNERS.PEDIDO;
DROP TABLE DB_OWNERS.LOCAL_;
DROP TABLE DB_OWNERS.CATEGORIA_LOCAL;
DROP TABLE DB_OWNERS.TIPO_LOCAL;
DROP TABLE DB_OWNERS.CATEGORIA;
DROP TABLE DB_OWNERS.OPERADOR;
DROP TABLE DB_OWNERS.DIRECCION_POR_USUARIO;
DROP TABLE DB_OWNERS.DIRECCION;
DROP TABLE DB_OWNERS.LOCALIDAD;
DROP TABLE DB_OWNERS.PROVINCIA;
DROP TABLE DB_OWNERS.ENVIO_MENSAJERIA;
DROP TABLE DB_OWNERS.TIPO_PAQUETE;
DROP TABLE DB_OWNERS.MEDIO_DE_PAGO;
DROP TABLE DB_OWNERS.DATOS_TARJETA;
DROP TABLE DB_OWNERS.USUARIO;
DROP TABLE DB_OWNERS.REPARTIDOR;
DROP TABLE DB_OWNERS.PRODUCTO;
DROP TABLE DB_OWNERS.ITEM;
DROP TABLE DB_OWNERS.MOVILIDAD;
DROP TABLE DB_OWNERS.HORARIO_ATENCION;
DROP TABLE DB_OWNERS.DIA_SEMANA;
DROP TABLE DB_OWNERS.PRODUCTO_POR_LOCAL;
DROP TABLE DB_OWNERS.TIPO_RECLAMO;
DROP TABLE DB_OWNERS.ESTADO;



DROP TABLE DB_OWNERS.BI_CATEGORIA_LOCAL;
DROP TABLE DB_OWNERS.BI_DIA;
DROP TABLE DB_OWNERS.BI_ENVIOS_MENSAJERIA;
DROP TABLE DB_OWNERS.BI_ESTADO_ENVIO;
DROP TABLE DB_OWNERS.BI_LOCAL;
DROP TABLE DB_OWNERS.BI_LOCALIDAD;
DROP TABLE DB_OWNERS.BI_MEDIO_DE_PAGO;
DROP TABLE DB_OWNERS.BI_PEDIDOS;
DROP TABLE DB_OWNERS.BI_RANGO_ETARIO;
DROP TABLE DB_OWNERS.BI_RANGO_HORARIO;
DROP TABLE DB_OWNERS.BI_RECLAMOS;
DROP TABLE DB_OWNERS.BI_TIEMPO;
DROP TABLE DB_OWNERS.BI_TIPO_MOVILIDAD;
DROP TABLE DB_OWNERS.BI_TIPO_PAQUETE;
DROP TABLE DB_OWNERS.BI_TIPO_RECLAMO;

DROP PROCEDURE DB_OWNERS.migrar_bi_envios_mensajeria
DROP PROCEDURE DB_OWNERS.migrar_bi_pedidos
DROP PROCEDURE DB_OWNERS.migrar_bi_reclamos

DROP VIEW vista_pedidos_mayor_dia_y_fh_por_localidad_categoria_mes
DROP VIEW vista_pedidos_monto_no_cobrado_por_local_dia_fh
DROP VIEW vista_promedio_coste_envio_por_localidad_mes
DROP VIEW vista_desvio_promedio_tiempo_entrega_por_movilidad_dia_fh
DROP VIEW vista_monto_cupones_por_mes_reu
DROP VIEW vista_calificacion_por_mes_local
DROP VIEW vista_pedidos_mensajeria_entregados_por_re_repartidor_localidad
DROP VIEW vista_promedio_valor_asegurado_por_mes_tipopaquete
DROP VIEW vista_reclamos_recibidos_por_mes_local_dia_rh
DROP VIEW vista_tiempo_resolucion_reclamo_por_mes_tiporeclamo_reo
DROP VIEW vista_monto_cupones_reclamo_por_mes


