--ELIMINA TODOS LOS SP CREADOS
DROP PROCEDURE DB_OWNERS.migrar_usuario;
DROP PROCEDURE DB_OWNERS.migrar_provincias;
DROP PROCEDURE DB_OWNERS.migrar_localidades;
DROP PROCEDURE DB_OWNERS.migrar_direcciones;
DROP PROCEDURE DB_OWNERS.migrar_tipos_local;
DROP PROCEDURE DB_OWNERS.migrar_locales;
DROP PROCEDURE DB_OWNERS.migrar_dias_semana;
DROP PROCEDURE DB_OWNERS.migrar_horarios_atencion;
DROP PROCEDURE DB_OWNERS.migrar_tipo_cupon;
DROP PROCEDURE DB_OWNERS.migrar_cupon;
DROP PROCEDURE DB_OWNERS.migrar_cupones_reclamo;
DROP PROCEDURE DB_OWNERS.migrar_cupones_usados;
DROP PROCEDURE DB_OWNERS.migrar_datos_tarjeta;
DROP PROCEDURE DB_OWNERS.migrar_direcciones2;
DROP PROCEDURE DB_OWNERS.migrar_direcciones_por_usuario;
DROP PROCEDURE DB_OWNERS.migrar_envio_mensajeria;
DROP PROCEDURE DB_OWNERS.migrar_estado;
DROP PROCEDURE DB_OWNERS.migrar_items;
DROP PROCEDURE DB_OWNERS.migrar_movilidad;
DROP PROCEDURE DB_OWNERS.migrar_pedidos;
DROP PROCEDURE DB_OWNERS.migrar_productos;
DROP PROCEDURE DB_OWNERS.migrar_productos_por_local;
DROP PROCEDURE DB_OWNERS.migrar_reclamos;
DROP PROCEDURE DB_OWNERS.migrar_solucion_reclamo;
DROP PROCEDURE DB_OWNERS.migrar_repartidor;
DROP PROCEDURE DB_OWNERS.migrar_tipo_paquete;
DROP PROCEDURE DB_OWNERS.migrar_tipo_reclamo;
DROP PROCEDURE DB_OWNERS.migrar_medio_de_pago;
DROP PROCEDURE DB_OWNERS.migrar_operador;
DROP PROCEDURE DB_OWNERS.migrar_categorias;
DROP PROCEDURE DB_OWNERS.migrar_categorias_local;

DELETE FROM DB_OWNERS.CUPON
	DBCC CHECKIDENT ('DB_OWNERS.CUPON', RESEED, 0)


DROP TABLE DB_OWNERS.TIPO_CUPON;
DROP TABLE DB_OWNERS.CUPON_USADO;
DROP TABLE DB_OWNERS.CUPON_RECLAMO;
DROP TABLE DB_OWNERS.RECLAMO;
DROP TABLE DB_OWNERS.CUPON;
DROP TABLE DB_OWNERS.PEDIDO;
DROP TABLE DB_OWNERS.LOCAL_;
DROP TABLE DB_OWNERS.TIPO_LOCAL;
DROP TABLE DB_OWNERS.OPERADOR;
DROP TABLE DB_OWNERS.DIRECCION_POR_USUARIO;
DROP TABLE DB_OWNERS.DIRECCION;
DROP TABLE DB_OWNERS.LOCALIDAD;
DROP TABLE DB_OWNERS.PROVINCIA;
DROP TABLE DB_OWNERS.ENVIO_MENSAJERIA;
DROP TABLE DB_OWNERS.TIPO_PAQUETE;
DROP TABLE DB_OWNERS.MEDIO_DE_PAGO;
DROP TABLE DB_OWNERS.DATOS_TARJETA;
DROP TABLE DB_OWNERS.USUARIO;
DROP TABLE DB_OWNERS.REPARTIDOR;
DROP TABLE DB_OWNERS.PRODUCTO;
DROP TABLE DB_OWNERS.ITEM;
DROP TABLE DB_OWNERS.MOVILIDAD;
DROP TABLE DB_OWNERS.HORARIO_ATENCION;
DROP TABLE DB_OWNERS.DIA_SEMANA;
DROP TABLE DB_OWNERS.PRODUCTO_POR_LOCAL;
DROP TABLE DB_OWNERS.TIPO_RECLAMO;
DROP TABLE DB_OWNERS.SOLUCION;
DROP TABLE DB_OWNERS.ESTADO;
DROP TABLE DB_OWNERS.CATEGORIA;
DROP TABLE DB_OWNERS.CATEGORIA_LOCAL;


