--------------------------------------
------------ PROCEDURES --------------
--------------------------------------

--LOCALES
CREATE PROCEDURE DB_OWNERS.migrar_tipos_local AS
BEGIN
	INSERT INTO DB_OWNERS.TIPO_LOCAL(
		descripcion
	)
	SELECT DISTINCT 
		m.LOCAL_TIPO
	FROM gd_esquema.Maestra m 
	WHERE m.LOCAL_TIPO IS NOT NULL
END
GO


CREATE PROCEDURE DB_OWNERS.migrar_locales AS
BEGIN
	INSERT INTO DB_OWNERS.LOCAL_(
		nombre,
		descripcion,
		id_direccion,
		id_tipo_local
	)
	SELECT DISTINCT 
		m.LOCAL_NOMBRE,
		m.LOCAL_DESCRIPCION,
		D.id_direccion,
		CL.id_tipo_local
	FROM gd_esquema.Maestra m JOIN DB_OWNERS.DIRECCION D ON D.calle_numero = m.LOCAL_DIRECCION 
	JOIN DB_OWNERS.TIPO_LOCAL CL ON CL.descripcion = m.LOCAL_TIPO
	WHERE m.LOCAL_NOMBRE IS NOT NULL AND m.LOCAL_DESCRIPCION IS NOT NULL
END
GO

--RECLAMOS


CREATE PROCEDURE DB_OWNERS.migrar_estado_reclamo AS
BEGIN
	INSERT INTO DB_OWNERS.ESTADO_RECLAMO
	SELECT DISTINCT 
		RECLAMO_ESTADO
	FROM gd_esquema.Maestra
	WHERE RECLAMO_ESTADO IS NOT NULL
END
GO


CREATE PROCEDURE DB_OWNERS.migrar_tipo_reclamo AS
BEGIN
	INSERT INTO DB_OWNERS.TIPO_RECLAMO
	SELECT DISTINCT 
		RECLAMO_TIPO
	FROM gd_esquema.Maestra
	WHERE RECLAMO_TIPO IS NOT NULL
END
GO


CREATE PROCEDURE DB_OWNERS.migrar_solucion_reclamo AS
BEGIN
	INSERT INTO DB_OWNERS.SOLUCION
	SELECT DISTINCT 
		RECLAMO_SOLUCION
	FROM gd_esquema.Maestra
	WHERE RECLAMO_SOLUCION IS NOT NULL
END
GO

CREATE PROCEDURE DB_OWNERS.migrar_operador AS
BEGIN
	INSERT INTO DB_OWNERS.OPERADOR
	SELECT DISTINCT 
		m.OPERADOR_RECLAMO_NOMBRE,
		m.OPERADOR_RECLAMO_APELLIDO,
		m.OPERADOR_RECLAMO_DNI,
		m.OPERADOR_RECLAMO_TELEFONO,
		m.OPERADOR_RECLAMO_MAIL,
		m.OPERADOR_RECLAMO_FECHA_NAC,
		d.id_direccion
	FROM gd_esquema.Maestra m
	JOIN DB_OWNERS.DIRECCION d ON d.calle_numero = m.OPERADOR_RECLAMO_DIRECCION
	WHERE 
		m.OPERADOR_RECLAMO_NOMBRE IS NOT NULL and
		m.OPERADOR_RECLAMO_APELLIDO IS NOT NULL and
		m.OPERADOR_RECLAMO_DNI IS NOT NULL and
		m.OPERADOR_RECLAMO_TELEFONO IS NOT NULL and
		m.OPERADOR_RECLAMO_MAIL IS NOT NULL and
		m.OPERADOR_RECLAMO_FECHA_NAC IS NOT NULL
END
GO

--ENVIO PAQUETES
CREATE PROCEDURE DB_OWNERS.migrar_tipo_paquete AS
BEGIN
	INSERT INTO DB_OWNERS.TIPO_PAQUETE
	SELECT DISTINCT 
		m.PAQUETE_TIPO,
		m.PAQUETE_ALTO_MAX,
		m.PAQUETE_ANCHO_MAX,
		m.PAQUETE_LARGO_MAX,
		m.PAQUETE_PESO_MAX,
		m.PAQUETE_TIPO_PRECIO
	FROM gd_esquema.Maestra m
	WHERE 
		m.PAQUETE_TIPO IS NOT NULL and
		m.PAQUETE_ALTO_MAX IS NOT NULL and
		m.PAQUETE_ANCHO_MAX IS NOT NULL and
		m.PAQUETE_LARGO_MAX IS NOT NULL and
		m.PAQUETE_PESO_MAX IS NOT NULL and
		m.PAQUETE_TIPO_PRECIO IS NOT NULL
END
GO	

CREATE PROCEDURE DB_OWNERS.migrar_movilidad
AS BEGIN
	INSERT INTO DB_OWNERS.MOVILIDAD
	SELECT DISTINCT 
		m.REPARTIDOR_TIPO_MOVILIDAD
	FROM gd_esquema.Maestra m 
	WHERE m.REPARTIDOR_TIPO_MOVILIDAD IS NOT NULL
END
GO


CREATE PROCEDURE DB_OWNERS.migrar_repartidor
AS BEGIN
	INSERT INTO DB_OWNERS.REPARTIDOR
	SELECT DISTINCT 
		mov.id_movilidad,
		m.REPARTIDOR_NOMBRE,
		m.REPARTIDOR_APELLIDO,
		m.REPARTIDOR_DIRECION,
		m.REPARTIDOR_DNI,
		m.REPARTIDOR_TELEFONO,
		m.REPARTIDOR_EMAIL,
		m.REPARTIDOR_FECHA_NAC
	FROM gd_esquema.Maestra m
	JOIN DB_OWNERS.MOVILIDAD mov ON mov.vehiculo = m.REPARTIDOR_TIPO_MOVILIDAD
	WHERE 
		m.REPARTIDOR_NOMBRE IS NOT NULL and
		m.REPARTIDOR_APELLIDO IS NOT NULL and
		m.REPARTIDOR_DIRECION IS NOT NULL and
		m.REPARTIDOR_DNI IS NOT NULL and
		m.REPARTIDOR_TELEFONO IS NOT NULL and
		m.REPARTIDOR_EMAIL IS NOT NULL and
		m.REPARTIDOR_FECHA_NAC IS NOT NULL

END
GO	

CREATE PROCEDURE DB_OWNERS.migrar_trayecto AS
BEGIN
	INSERT INTO DB_OWNERS.TRAYECTO
	SELECT DISTINCT 
		d.id_direccion,
		d2.id_direccion,
		m.ENVIO_MENSAJERIA_KM
	FROM gd_esquema.Maestra m
	INNER JOIN DB_OWNERS.DIRECCION d ON d.calle_numero = m.ENVIO_MENSAJERIA_DIR_ORIG 
	INNER JOIN DB_OWNERS.DIRECCION d2 ON d2.calle_numero = m.ENVIO_MENSAJERIA_DIR_DEST
	WHERE 
		m.ENVIO_MENSAJERIA_KM IS NOT NULL
END
GO


CREATE PROCEDURE DB_OWNERS.migrar_estado AS
BEGIN
	INSERT INTO DB_OWNERS.ESTADO(
		estado
	)
	SELECT DISTINCT 
		m.ENVIO_MENSAJERIA_ESTADO
		FROM gd_esquema.Maestra m
		WHERE m.ENVIO_MENSAJERIA_ESTADO IS NOT NULL
	UNION
	SELECT DISTINCT 
		m.PEDIDO_ESTADO
		FROM gd_esquema.Maestra m
		WHERE m.PEDIDO_ESTADO IS NOT NULL
END
GO



--LUGARES

CREATE PROCEDURE DB_OWNERS.migrar_provincias AS
BEGIN
	INSERT INTO DB_OWNERS.PROVINCIA(
		nombre
	)
	SELECT DISTINCT 
		m.DIRECCION_USUARIO_PROVINCIA
		FROM gd_esquema.Maestra m
		WHERE m.DIRECCION_USUARIO_PROVINCIA IS NOT NULL
	UNION
	SELECT DISTINCT 
		m.ENVIO_MENSAJERIA_PROVINCIA
		FROM gd_esquema.Maestra m
		WHERE m.ENVIO_MENSAJERIA_PROVINCIA IS NOT NULL
	UNION
	SELECT DISTINCT 
		m.LOCAL_PROVINCIA
		FROM gd_esquema.Maestra m
		WHERE m.LOCAL_PROVINCIA IS NOT NULL
END
GO



CREATE PROCEDURE DB_OWNERS.migrar_localidades AS
BEGIN
	INSERT INTO DB_OWNERS.LOCALIDAD(
		nombre, 
		id_provincia
	)
	SELECT DISTINCT
             M.LOCAL_LOCALIDAD,
             P.id_provincia
         FROM
             gd_esquema.Maestra M
			 JOIN DB_OWNERS.PROVINCIA P ON P.nombre = M.LOCAL_PROVINCIA
         WHERE
             M.LOCAL_LOCALIDAD IS NOT NULL
	UNION
	SELECT DISTINCT
			M.DIRECCION_USUARIO_LOCALIDAD,
			P.id_provincia
		FROM
			gd_esquema.Maestra M
			JOIN DB_OWNERS.PROVINCIA P ON P.nombre = M.DIRECCION_USUARIO_PROVINCIA
		WHERE
			M.DIRECCION_USUARIO_LOCALIDAD IS NOT NULL
	UNION
	SELECT DISTINCT
			M.ENVIO_MENSAJERIA_LOCALIDAD,
			P.id_provincia
		FROM
			gd_esquema.Maestra M
			JOIN DB_OWNERS.PROVINCIA P ON P.nombre = M.ENVIO_MENSAJERIA_PROVINCIA
		WHERE
			M.ENVIO_MENSAJERIA_LOCALIDAD IS NOT NULL
END
GO


/*
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'migrar_direcciones')
DROP PROCEDURE DB_OWNERS.migrar_direcciones
GO*/
CREATE PROCEDURE DB_OWNERS.migrar_direcciones AS
BEGIN
/*
DELETE FROM DB_OWNERS.DIRECCION
	DBCC CHECKIDENT ('DB_OWNERS.DIRECCION', RESEED, 0)*/
INSERT INTO DB_OWNERS.DIRECCION(
	calle_numero,
	id_localidad
	)
	SELECT DISTINCT
		m.DIRECCION_USUARIO_DIRECCION,
		L.id_localidad
	from gd_esquema.Maestra m
	JOIN DB_OWNERS.LOCALIDAD L ON L.nombre = m.DIRECCION_USUARIO_LOCALIDAD
	where DIRECCION_USUARIO_DIRECCION is NOT NULL
	UNION
	SELECT DISTINCT
		m.LOCAL_DIRECCION,
		L.id_localidad
	from gd_esquema.Maestra m
	JOIN DB_OWNERS.LOCALIDAD L ON L.nombre = m.LOCAL_LOCALIDAD
	where LOCAL_DIRECCION is NOT NULL
	UNION
	SELECT DISTINCT
		m.ENVIO_MENSAJERIA_DIR_DEST,
		L.id_localidad
	from gd_esquema.Maestra m
	JOIN DB_OWNERS.LOCALIDAD L ON L.nombre = m.ENVIO_MENSAJERIA_LOCALIDAD
	where ENVIO_MENSAJERIA_DIR_DEST is NOT NULL
	UNION
	SELECT DISTINCT
		m.ENVIO_MENSAJERIA_DIR_ORIG,
		L.id_localidad
	from gd_esquema.Maestra m
	JOIN DB_OWNERS.LOCALIDAD L ON L.nombre = m.ENVIO_MENSAJERIA_LOCALIDAD
	where ENVIO_MENSAJERIA_DIR_ORIG is NOT NULL
END
GO


/*
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'migrar_direcciones2')
DROP PROCEDURE DB_OWNERS.migrar_direcciones2
GO*/
CREATE PROCEDURE DB_OWNERS.migrar_direcciones2 AS
BEGIN
INSERT INTO DB_OWNERS.DIRECCION(
	calle_numero
	)
	SELECT DISTINCT
		m.OPERADOR_RECLAMO_DIRECCION
	from gd_esquema.Maestra m
	where OPERADOR_RECLAMO_DIRECCION is NOT NULL 
	UNION
	SELECT DISTINCT
		m.REPARTIDOR_DIRECION
	from gd_esquema.Maestra m
	where REPARTIDOR_DIRECION is NOT NULL
END
GO



	

BEGIN TRANSACTION 
--RECLAMOS
	--EXECUTE DB_OWNERS.migrar_estado_reclamo
	--EXECUTE DB_OWNERS.migrar_tipo_reclamo
	--EXECUTE DB_OWNERS.migrar_solucion_reclamo


--LUGARES
	--EXECUTE DB_OWNERS.migrar_provincias
	--EXECUTE DB_OWNERS.migrar_localidades
	--EXECUTE DB_OWNERS.migrar_direcciones
	--EXECUTE DB_OWNERS.migrar_direcciones2
	--EXECUTE DB_OWNERS.migrar_operador
	


--ENVIO PAQUETES
	--EXECUTE DB_OWNERS.migrar_tipo_paquete
	--EXECUTE DB_OWNERS.migrar_movilidad
	--EXECUTE DB_OWNERS.migrar_repartidor
	--EXECUTE DB_OWNERS.migrar_trayecto
	--EXECUTE DB_OWNERS.migrar_estado



--LOCALES
	--EXECUTE DB_OWNERS.migrar_tipos_local
	--EXECUTE DB_OWNERS.migrar_categorias
	--EXECUTE DB_OWNERS.migrar_locales
	--EXECUTE DB_OWNERS.migrar_repartidor
COMMIT TRANSACTION



